project_name: cpubar

before:
  hooks:
    - go mod tidy

builds:
  - binary: cpubar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: binary

release:
  prerelease: auto
